name: Linters

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - name: eslint
        uses: reviewdog/action-eslint@v1.2.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
